In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
df = pd.read_csv('../../data/metadata-clean.csv')
df.head()

,name,item_id,supported_languages,developers,publishers,categories,genres,total_recommendations,released_date,tags,price
0,Clash of Warlords,1430720,"['Simplified Chinese', 'Traditional Chinese']",['XINLINE GAMES'],['XINLINE GAMES'],"['Single-player', 'In-App Purchases', 'Family ...",['Strategy'],0,2021-02-07,"['Turn-Based Tactics', 'Strategy', 'Wargame', ...",699.0
1,Mine Crazy: The Korean Grinder,1430740,['English'],['Dano Sato'],['RealMono Inc.'],"['Single-player', 'Family Sharing']","['Casual', 'Indie', 'RPG', 'Simulation']",0,2020-10-08,"['Casual', 'RPG', 'Simulation', 'Clicker', 'Fa...",199.0
2,Fade,1430100,['English'],['Azimyth Studios'],['Azimyth Studios'],"['Single-player', 'Family Sharing']","['Indie', 'RPG']",0,2020-10-29,"['Horror', 'RPG', 'Survival Horror', 'Top-Down...",199.0
3,Clash: Artifacts of Chaos,1430680,"['English', 'French', 'Italian', 'German', 'Sp...",['ACE Team'],['Nacon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Adventure', 'Indie']",759,2023-03-09,"['Action', 'Adventure', 'RPG', 'Souls-like', '...",2999.0
4,Astatos,1430970,"['English', 'Simplified Chinese', 'Traditional...",['Studio Klondike Australia'],['Studio Klondike'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Adventure', 'Indie', 'Strategy', 'Early Acce...",243,2021-12-16,"['Early Access', 'Visual Novel', 'Card Battler...",1499.0

## Numerical feature encoding

In [3]:
def min_max(values: pd.Series):
    min_time = values.min()
    max_time = values.max()
    normalized = (values - min_time) / (max_time - min_time)
    return normalized

def z_score(values: pd.Series):
    mean_time = values.mean()
    std_time = values.std()
    standardized = (values - mean_time) / std_time
    return standardized

def log_normalize(values: pd.Series):
    min_time = values.min()
    offset_timestamps = values - min_time
    epsilon = 1e-10
    return np.log(offset_timestamps + epsilon)

### Total recommendation

In [4]:
df['mm_total_recommendation'] = min_max(df['total_recommendations'])
df['z_total_recommendation'] = z_score(df['total_recommendations'])
df['log_total_recommendation'] = log_normalize(df['total_recommendations'])

df.head()

,name,item_id,supported_languages,developers,publishers,categories,genres,total_recommendations,released_date,tags,price,mm_total_recommendation,z_total_recommendation,log_total_recommendation
0,Clash of Warlords,1430720,"['Simplified Chinese', 'Traditional Chinese']",['XINLINE GAMES'],['XINLINE GAMES'],"['Single-player', 'In-App Purchases', 'Family ...",['Strategy'],0,2021-02-07,"['Turn-Based Tactics', 'Strategy', 'Wargame', ...",699.0,0.000000,-0.046711,-23.025851
1,Mine Crazy: The Korean Grinder,1430740,['English'],['Dano Sato'],['RealMono Inc.'],"['Single-player', 'Family Sharing']","['Casual', 'Indie', 'RPG', 'Simulation']",0,2020-10-08,"['Casual', 'RPG', 'Simulation', 'Clicker', 'Fa...",199.0,0.000000,-0.046711,-23.025851
2,Fade,1430100,['English'],['Azimyth Studios'],['Azimyth Studios'],"['Single-player', 'Family Sharing']","['Indie', 'RPG']",0,2020-10-29,"['Horror', 'RPG', 'Survival Horror', 'Top-Down...",199.0,0.000000,-0.046711,-23.025851
3,Clash: Artifacts of Chaos,1430680,"['English', 'French', 'Italian', 'German', 'Sp...",['ACE Team'],['Nacon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Adventure', 'Indie']",759,2023-03-09,"['Action', 'Adventure', 'RPG', 'Souls-like', '...",2999.0,0.000174,-0.011641,6.632002
4,Astatos,1430970,"['English', 'Simplified Chinese', 'Traditional...",['Studio Klondike Australia'],['Studio Klondike'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Adventure', 'Indie', 'Strategy', 'Early Acce...",243,2021-12-16,"['Early Access', 'Visual Novel', 'Card Battler...",1499.0,0.000056,-0.035483,5.493061

### Price

In [5]:
df['mm_price'] = min_max(df['price'])
df['z_price'] = z_score(df['price'])
df['log_price'] = log_normalize(df['price'])

df.head()

,name,item_id,supported_languages,developers,publishers,categories,genres,total_recommendations,released_date,tags,price,mm_total_recommendation,z_total_recommendation,log_total_recommendation,mm_price,z_price,log_price
0,Clash of Warlords,1430720,"['Simplified Chinese', 'Traditional Chinese']",['XINLINE GAMES'],['XINLINE GAMES'],"['Single-player', 'In-App Purchases', 'Family ...",['Strategy'],0,2021-02-07,"['Turn-Based Tactics', 'Strategy', 'Wargame', ...",699.0,0.000000,-0.046711,-23.025851,0.003679,-0.049534,6.549651
1,Mine Crazy: The Korean Grinder,1430740,['English'],['Dano Sato'],['RealMono Inc.'],"['Single-player', 'Family Sharing']","['Casual', 'Indie', 'RPG', 'Simulation']",0,2020-10-08,"['Casual', 'RPG', 'Simulation', 'Clicker', 'Fa...",199.0,0.000000,-0.046711,-23.025851,0.001047,-0.390004,5.293305
2,Fade,1430100,['English'],['Azimyth Studios'],['Azimyth Studios'],"['Single-player', 'Family Sharing']","['Indie', 'RPG']",0,2020-10-29,"['Horror', 'RPG', 'Survival Horror', 'Top-Down...",199.0,0.000000,-0.046711,-23.025851,0.001047,-0.390004,5.293305
3,Clash: Artifacts of Chaos,1430680,"['English', 'French', 'Italian', 'German', 'Sp...",['ACE Team'],['Nacon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Adventure', 'Indie']",759,2023-03-09,"['Action', 'Adventure', 'RPG', 'Souls-like', '...",2999.0,0.000174,-0.011641,6.632002,0.015784,1.516628,8.006034
4,Astatos,1430970,"['English', 'Simplified Chinese', 'Traditional...",['Studio Klondike Australia'],['Studio Klondike'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Adventure', 'Indie', 'Strategy', 'Early Acce...",243,2021-12-16,"['Early Access', 'Visual Novel', 'Card Battler...",1499.0,0.000056,-0.035483,5.493061,0.007889,0.495218,7.312553

## Date features encoding

In [6]:
df['released_date'] = pd.to_datetime(df['released_date'])
df['released_timestamp'] = df['released_date'].apply(lambda x: x.timestamp())

In [7]:
df['mm_released_date'] = min_max(df['released_timestamp'])
df['z_released_date'] = z_score(df['released_timestamp'])
df['log_released_date'] = log_normalize(df['released_timestamp'])

df.head()

,name,item_id,supported_languages,developers,publishers,categories,genres,total_recommendations,released_date,tags,...,mm_total_recommendation,z_total_recommendation,log_total_recommendation,mm_price,z_price,log_price,released_timestamp,mm_released_date,z_released_date,log_released_date
0,Clash of Warlords,1430720,"['Simplified Chinese', 'Traditional Chinese']",['XINLINE GAMES'],['XINLINE GAMES'],"['Single-player', 'In-App Purchases', 'Family ...",['Strategy'],0,2021-02-07,"['Turn-Based Tactics', 'Strategy', 'Wargame', ...",...,0.000000,-0.046711,-23.025851,0.003679,-0.049534,6.549651,1.612656e+09,0.855371,0.003497,20.428931
1,Mine Crazy: The Korean Grinder,1430740,['English'],['Dano Sato'],['RealMono Inc.'],"['Single-player', 'Family Sharing']","['Casual', 'Indie', 'RPG', 'Simulation']",0,2020-10-08,"['Casual', 'RPG', 'Simulation', 'Clicker', 'Fa...",...,0.000000,-0.046711,-23.025851,0.001047,-0.390004,5.293305,1.602115e+09,0.843270,-0.103532,20.414682
2,Fade,1430100,['English'],['Azimyth Studios'],['Azimyth Studios'],"['Single-player', 'Family Sharing']","['Indie', 'RPG']",0,2020-10-29,"['Horror', 'RPG', 'Survival Horror', 'Top-Down...",...,0.000000,-0.046711,-23.025851,0.001047,-0.390004,5.293305,1.603930e+09,0.845353,-0.085109,20.417149
3,Clash: Artifacts of Chaos,1430680,"['English', 'French', 'Italian', 'German', 'Sp...",['ACE Team'],['Nacon'],"['Single-player', 'Steam Achievements', 'Steam...","['Action', 'Adventure', 'Indie']",759,2023-03-09,"['Action', 'Adventure', 'RPG', 'Souls-like', '...",...,0.000174,-0.011641,6.632002,0.015784,1.516628,8.006034,1.678320e+09,0.930761,0.670236,20.513398
4,Astatos,1430970,"['English', 'Simplified Chinese', 'Traditional...",['Studio Klondike Australia'],['Studio Klondike'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Adventure', 'Indie', 'Strategy', 'Early Acce...",243,2021-12-16,"['Early Access', 'Visual Novel', 'Card Battler...",...,0.000056,-0.035483,5.493061,0.007889,0.495218,7.312553,1.639613e+09,0.886321,0.277211,20.464474

In [8]:
# df['released_year'] = df['released_date'].dt.year.astype('category')
# df.head()

In [9]:
# df['released_decade'] = (df['released_date'].dt.year // 10 * 10).astype('category')
# df.head()

In [10]:
# df['released_year'] = df['released_date'].dt.year.astype('category')
# df['released_month'] = df['released_date'].dt.month.astype('category')
# df['released_day_of_week'] = df['released_date'].dt.dayofweek.astype('category')
# df['released_quarter'] = df['released_date'].dt.quarter.astype('category')
# df.head()

In [11]:
# df_interactions = pd.read_csv('data/review-clean.csv')
# df_interactions.head()

In [12]:
# max_timestamp = df_interactions['timestamp'].max() # Latest date in the interaction data
# reference_date = pd.to_datetime(max_timestamp, unit='s')
# reference_date

In [13]:
# df['age'] = (reference_date - pd.to_datetime(df['released_date'])).dt.days.clip(lower=0) // 365.25
# df.head()

In [14]:
# age_buckets = ['new_release', 'recent', 'established', 'classic']
# df['age_category'] = pd.cut(
#     df['age'],
#     bins=[0, 1, 3, 10, float('inf')],
#     labels=age_buckets
# ).astype('category')
# df.head()

In [15]:
# df['mm_age'] = min_max(df['age'])
# df['z_age'] = z_score(df['age'])
# df['log_age'] = log_normalize(df['age'])
#
# df.head()

## Categorical feature encoding

In [16]:
df['publishers'] = df['publishers'].apply(ast.literal_eval)
df['developers'] = df['developers'].apply(ast.literal_eval)
df['tags'] = df['tags'].apply(ast.literal_eval)
df['supported_languages'] = df['supported_languages'].apply(ast.literal_eval)
df['genres'] = df['genres'].apply(ast.literal_eval)
df['categories'] = df['categories'].apply(ast.literal_eval)

In [17]:
unique_publishers = df['publishers'].explode().unique()
unique_developers = df['developers'].explode().unique()
unique_tags = df['tags'].explode().unique()
unique_supported_languages = df['supported_languages'].explode().unique()
unique_genres = df['genres'].explode().unique()
unique_categories = df['categories'].explode().unique()

In [21]:
publishers_mapper = {publisher: i for i, publisher in enumerate(unique_publishers)}
developers_mapper = {developer: i for i, developer in enumerate(unique_developers)}
tags_mapper = {tag: i for i, tag in enumerate(unique_tags)}
languages_mapper = {language: i for i, language in enumerate(unique_supported_languages)}
genres_mapper = {genre: i for i, genre in enumerate(unique_genres)}
categories_mapper = {category: i for i, category in enumerate(unique_categories)}

In [23]:
df['publishers'] = df['publishers'].apply(lambda x: [publishers_mapper[pub] for pub in x])
df['developers'] = df['developers'].apply(lambda x: [developers_mapper[dev] for dev in x])
df['tags'] = df['tags'].apply(lambda x: [tags_mapper[tag] for tag in x])
df['supported_languages'] = df['supported_languages'].apply(lambda x: [languages_mapper[lang] for lang in x])
df['genres'] = df['genres'].apply(lambda x: [genres_mapper[gen] for gen in x])
df['categories'] = df['categories'].apply(lambda x: [categories_mapper[cat] for cat in x])

# Merge to interaction

In [24]:
df_interactions = pd.read_csv('../../data/interaction-clean.csv')
df_interactions.head()

,user_id,review,timestamp,rating,item_id,rating_exp,rating_imp,mm_timestamp,z_timestamp,log_timestamp
0,76561197960432447,A legendary tactical shooter that shaped the g...,1738278781,True,10,1,1,0.998997,0.559647,19.927005
1,76561198071230926,"The best CS sure, but server browser is the il...",1736206418,True,10,1,1,0.994407,0.535447,19.922399
2,76561198206216352,Some of the best memories of my childhood were...,1738041574,True,10,1,1,0.998472,0.556877,19.926479
3,76561198110801124,This game feels so much better than CS2. I kno...,1738015332,True,10,1,1,0.998414,0.556570,19.926420
4,76561199813732773,its very fun to play you can make friends out ...,1737853720,True,10,1,1,0.998056,0.554683,19.926062

In [25]:
items_in_interaction = df_interactions['item_id'].unique()
items_in_metadata = df['item_id'].unique()

In [26]:
items_missing_metadata = set(items_in_interaction) - set(items_in_metadata)
len(items_missing_metadata)

605

In [27]:
df_merged = pd.merge(df_interactions, df, on='item_id', how='left')
df_merged.head()

,user_id,review,timestamp,rating,item_id,rating_exp,rating_imp,mm_timestamp,z_timestamp,log_timestamp,...,mm_total_recommendation,z_total_recommendation,log_total_recommendation,mm_price,z_price,log_price,released_timestamp,mm_released_date,z_released_date,log_released_date
0,76561197960432447,A legendary tactical shooter that shaped the g...,1738278781,True,10,1,1,0.998997,0.559647,19.927005,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,973036800.0,0.12102,-6.491067,18.473349
1,76561198071230926,"The best CS sure, but server browser is the il...",1736206418,True,10,1,1,0.994407,0.535447,19.922399,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,973036800.0,0.12102,-6.491067,18.473349
2,76561198206216352,Some of the best memories of my childhood were...,1738041574,True,10,1,1,0.998472,0.556877,19.926479,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,973036800.0,0.12102,-6.491067,18.473349
3,76561198110801124,This game feels so much better than CS2. I kno...,1738015332,True,10,1,1,0.998414,0.556570,19.926420,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,973036800.0,0.12102,-6.491067,18.473349
4,76561199813732773,its very fun to play you can make friends out ...,1737853720,True,10,1,1,0.998056,0.554683,19.926062,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,973036800.0,0.12102,-6.491067,18.473349

In [28]:
df_merged[df_merged['tags'].isna()]

,user_id,review,timestamp,rating,item_id,rating_exp,rating_imp,mm_timestamp,z_timestamp,log_timestamp,...,mm_total_recommendation,z_total_recommendation,log_total_recommendation,mm_price,z_price,log_price,released_timestamp,mm_released_date,z_released_date,log_released_date
1747,76561197993732805,"If it were free, I would recommend it, but it ...",1418663157,False,100400,-1,0,0.291045,-3.172575,18.693730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1748,76561197961366898,As you can see I've played this game a lot. U...,1520573235,True,100400,1,1,0.516777,-1.982549,19.267864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1749,76561197994829189,Pro: \nGood program for beginers and industry ...,1405428735,True,100400,1,1,0.261730,-3.327117,18.587567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1750,76561198021622527,I bought this software ages ago... loved it wh...,1634774536,False,100400,-1,0,0.769734,-0.648995,19.666298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,76561198057822506,I bought Silo back when it was only $80 and du...,1564964168,False,100400,-1,0,0.615103,-1.464186,19.442043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1154304,76561198335465482,I still can't believe this exists. It is liter...,1731332290,True,993090,1,1,0.983611,0.478531,19.911483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154305,76561198061225363,"A very effective solution, it can get a 30fps ...",1731414171,True,993090,1,1,0.983792,0.479487,19.911667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154306,76561198174393245,If you are a fan of classic games and tired of...,1735834831,True,993090,1,1,0.993584,0.531108,19.921571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154318,76561199755184852,Road work now!,1736961983,True,993270,1,1,0.996080,0.544270,19.924081,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154319,76561198884562578,After spending 3 hours with Bob's Track Builde...,1734131546,True,993270,1,1,0.989811,0.511219,19.917767,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_merged.dropna(subset=['name'], inplace=True)
len(df_merged)

1149955

## Save file

In [30]:
df_merged

,user_id,review,timestamp,rating,item_id,rating_exp,rating_imp,mm_timestamp,z_timestamp,log_timestamp,...,mm_total_recommendation,z_total_recommendation,log_total_recommendation,mm_price,z_price,log_price,released_timestamp,mm_released_date,z_released_date,log_released_date
0,76561197960432447,A legendary tactical shooter that shaped the g...,1738278781,True,10,1,1,0.998997,0.559647,19.927005,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,9.730368e+08,0.121020,-6.491067,18.473349
1,76561198071230926,"The best CS sure, but server browser is the il...",1736206418,True,10,1,1,0.994407,0.535447,19.922399,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,9.730368e+08,0.121020,-6.491067,18.473349
2,76561198206216352,Some of the best memories of my childhood were...,1738041574,True,10,1,1,0.998472,0.556877,19.926479,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,9.730368e+08,0.121020,-6.491067,18.473349
3,76561198110801124,This game feels so much better than CS2. I kno...,1738015332,True,10,1,1,0.998414,0.556570,19.926420,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,9.730368e+08,0.121020,-6.491067,18.473349
4,76561199813732773,its very fun to play you can make friends out ...,1737853720,True,10,1,1,0.998056,0.554683,19.926062,...,0.036216,7.233859,11.967625,0.005258,0.154748,6.906755,9.730368e+08,0.121020,-6.491067,18.473349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156221,76561198047845894,"A fun and innovative game, not a bad thing to ...",1663545142,True,999890,1,1,0.833461,-0.313034,19.745840,...,0.000000,-0.046711,-23.025851,0.001574,-0.321910,5.700444,1.554941e+09,0.789108,-0.582531,20.348299
1156222,76561198314652319,"Developer, please listen to me, I love the con...",1689826252,True,999890,1,1,0.891674,-0.006144,19.813354,...,0.000000,-0.046711,-23.025851,0.001574,-0.321910,5.700444,1.554941e+09,0.789108,-0.582531,20.348299
1156223,76561198035100973,Disclaimer: My scores/reviews are almost alway...,1595699739,True,999990,1,1,0.683183,-1.105280,19.547015,...,0.000000,-0.046711,-23.025851,0.002626,-0.185722,6.212606,1.567296e+09,0.803293,-0.457079,20.366115
1156224,76561198414383514,Mediocre game with a pathetically bad challeng...,1706470035,False,999990,-1,0,0.928540,0.188209,19.853867,...,0.000000,-0.046711,-23.025851,0.002626,-0.185722,6.212606,1.567296e+09,0.803293,-0.457079,20.366115
1156225,76561197992216244,Pogood.,1720163517,True,999990,1,1,0.958872,0.348111,19.886010,...,0.000000,-0.046711,-23.025851,0.002626,-0.185722,6.212606,1.567296e+09,0.803293,-0.457079,20.366115

In [31]:
df_merged.to_csv('../../data/interaction-metadata.csv', index=False)

In [32]:
df.to_csv('../../data/metadata-features.csv', index=False)